### ISSUE TITLE
Queue support, enqueue by default

### ISSUE THREAD

**Issue by ltguillaume** [GM-Script-Writer-62850/HTML5-Music-Player#1]
This is pretty much the only little player that supports a filesystem with subfolders, nicely done! I was wondering if you're maybe thinking of adding a queue, and the option to enqueue a file by default, instead of immediately playing it back.

**Comment by GM-Script-Writer-62850** [comment]
No plans for that at this time

**Comment by ltguillaume** [comment]
Ah too bad, it'd really make the difference for me. Perhaps I'll have a
look at it and try to add it myself then. If so, I'll post the commit(s)
here.

**Comment by GM-Script-Writer-62850** [comment]
Take a look at how the play history and the no repeat features work, it stores an array of track id numbers and it plays the next (unless random) in the list
it should not be that hard to make one, adding a ui for it will be more work

**Comment by GM-Script-Writer-62850** [comment]
Wait a min you could in theory just push the track index into the history array and the history system should handle the que

**Comment by ltguillaume** [comment]
Good point. To be honest, I think that apart from visual feedback that the
track has been queued, an actual representation of the queue (as a list of
songs) wouldn't really be needed.

**Comment by GM-Script-Writer-62850** [comment]
if you go trying to add this feature into the history feature commenting this will help you see what you are doing
https://github.com/GM-Script-Writer-62850/HTML5-Music-Player/blob/master/index.html#L37

you may have a issue with the que being added before the current track, IIRC tracks at added to history when they end (wrapping that process in my head was a pain while making that feature, but it was the most efficient way to write the feature)

**Comment by ltguillaume** [comment]
Cool! That debug feature could just be made into a combination of playlist & play log! This is how I managed to implement a queue: https://github.com/ltGuillaume/HTML5-Music-Player/commit/7df974e5c69c3341953ab88f25d7532d0786e3b8

**Comment by GM-Script-Writer-62850** [comment]
Definitely accepting line 93 of player.js

So basically if queue is checked instead of changing to the next track it ques it instead
but does it work properly if you go back a track or two and add them?
the history feature was a bit of a pain at times as they are added to the list when they complete, so it messes with my thought process a bit when working on it, but it was more efficient performance wise than adding another event for just history

Was the change on line 380 necessary? play history navigation does not care about shuffle at least before your mod anyway

Only part of that debug could be use, very bad coding for battery life, it was quick and dirty

**Comment by ltguillaume** [comment]
That depends on the desired behavior. If you want queued songs to play immediately after a song ends, even when you pressed back a few times, then it won't work. But personally I don't want that. When going back several tracks in history and then queueing a few songs, they just add up neatly at the end of the history list and will play in due time. For me, that's the desired behavior.

Indeed, so in order to get to the proper index, I'm adding the currently played song the first time a song is queued. Otherwise it would skip the first queued song. That works nicely and won't "forget" the played song. `if(hst.indx>hst.log.length) hst.add();` already makes sure it won't be added again.

About line 380, I thought it would otherwise shuffle to another song, yes, but I believe that was before I decided to just add the currently playing song when no other songs were queued. It seems to not have any use now! Can be removed :-)

This really makes it an ideal party player: it will shuffle through, and as soon as a song is clicked, it'll queue up. After the queue is done, it'll go back to shuffle. I'll just need to change a bit, so that songs that can't be played by the browser get skipped (give the error, then immediately continue to next song).

**Comment by ltguillaume** [comment]
https://github.com/ltGuillaume/HTML5-Music-Player/commit/9ef7f52f7dbbf2a66aba7e02afb1b17255048167#diff-a9b24acc6c8d37de23098caa2f7907da

**Comment by GM-Script-Writer-62850** [comment]
I think i will add this in at some point, i may not use the same UI method

There is a potential issue with updates and the config quene not being in a users config and being undefined by default (vs true/false)
the 1st line was commented out and the rest are added
```
//config=config==null?base:JSON.parse(config);
config=config==null?{}:JSON.parse(config);
for(i in base){
   if(config[i]===undefined){
      config[i]=base[i];
   }
}
```
This will add a feature into the current configuration if it was not present on lat page load

**Comment by ltguillaume** [comment]
Good point!

**Comment by GM-Script-Writer-62850** [comment]
Default is not queue, but it is configurable
There may be a edge use case that can get the history system confused

**Comment by ltguillaume** [comment]
> And here was was thinking eqeue was hard to spell!

Nice ;-) I'll check out your new commits in the morning, looking good!

**Comment by GM-Script-Writer-62850** [comment]
speaking of spelling errors...
![screenshot_2018-06-02_21-12-25](https://user-images.githubusercontent.com/564653/40882245-cabadc6c-66a9-11e8-9ccc-3edda670563f.png)
